### ISSUE TITLE
Missing Visits

### ISSUE THREAD

**Issue by denstepa** [ankane/ahoy#203]
Hi! We've just discovered that we have a problem that sometimes in around 5% of cases we dont have a visit information, but have the event.

What could cause that ? 

`select count(distinct visit_id), count(ahoy_events.id), date(time) from ahoy_events left join visits on ahoy_events.visit_id = visits.id
where visits.id is null
group by 3 order by 3`

**Comment by ankane** [comment]
The two I can think of are:

1. `Ahoy.track_visits_immediately = false` (default) and the JavaScript library isn't included on all pages where a visit can begin
2. Visits are expiring and a new one is not created, due to a bug which was recently fixed in #189 (currently on master)

**Comment by denstepa** [comment]
Hey, thanks for your comet, and sorry for a long reply
We've updated ahoy to 1.5.1 and the problem mostly gone, at least we thought so.
Few days ago we checked database, and we are still getting 5-10% of visits missing.
What is more strange, in logs i found the request for a visit creation, but in database save event has a different visit_id. Do you have an idea of why this could happen ? 

```
Processing by Ahoy::VisitsController#create as JSON
  Parameters: {"visit_token"=>"dc3a3f5a-cf51-4bb1-9d11-89613c77e13c", "visitor_token"=>"068326bc-8cc8-4f63-b746-31e1ca993c2d", "platform"=>"Web", "landing_page"=>"https://www.inkitt.com/stories/fanfiction/32408/chapters/15?ref=v_40bec0a9-6107-40da-81aa-0a8a5da61c0e&utm_campaign=dark&utm_medium=visitor&utm_source=dark&utm_term=a64c1825-5429-404f-a950-187e00da940d", "screen_width"=>"384", "screen_height"=>"800"}
--
Started POST "/ahoy/events"
Processing by Ahoy::EventsController#create as JSON
  Parameters: {"_json"=>[{"id"=>"496c9dae-5045-435f-a392-f3feea697e69", "visit_token"=>"dc3a3f5a-cf51-4bb1-9d11-89613c77e13c", "visitor_token"=>"068326bc-8cc8-4f63-b746-31e1ca993c2d", "name"=>"First Time Visit Start", "properties"=>{"initial_utm_source"=>"dark"}, "time"=>1479114161.766}], "event"=>{}}
```

In Database / Rails we i find this
```
[1] pry(main)> Ahoy::Event.find('496c9dae-5045-435f-a392-f3feea697e69')
  Ahoy::Event Load (313.1ms)  SELECT "ahoy_events".* FROM "ahoy_events" WHERE "ahoy_events"."id" = $1 LIMIT 1  [["id", "496c9dae-5045-435f-a392-f3feea697e69"]]
=> #<Ahoy::Event id: #<UUID:0x3fddc91d7ce8 UUID:496c9dae-5045-435f-a392-f3feea697e69>, visit_id: #<UUID:0x3fddc91eff8c UUID:71baa1a4-c80c-432d-b6c1-b7d05148574d>, user_id: nil, name: "First Time Visit Start", properties: {"initial_utm_source"=>"dark"}, time: "2016-11-14 09:02:41">
[2] pry(main)> Visit.find('dc3a3f5a-cf51-4bb1-9d11-89613c77e13c')
  Visit Load (271.0ms)  SELECT "visits".* FROM "visits" WHERE "visits"."id" = $1 LIMIT 1  [["id", "dc3a3f5a-cf51-4bb1-9d11-89613c77e13c"]]
=> #<Visit id: #<UUID:0x3fddc9de8050 UUID:dc3a3f5a-cf51-4bb1-9d11-89613c77e13c>, visitor_id: #<UUID:0x3fddc9ded960 UUID:068326bc-8cc8-4f63-b746-31e1ca993c2d>, ip: "66.102.6.211", user_agent: "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 B...", referrer: nil, landing_page: "https://www.inkitt.com/stories/fanfiction/32408/cha...", user_id: nil, referring_domain: nil, search_keyword: nil, browser: "Chrome Mobile", os: "Android", device_type: "Mobile", country: "United States", region: "California", city: "Mountain View", utm_source: "dark", utm_medium: "visitor", utm_term: "a64c1825-5429-404f-a950-187e00da940d", utm_content: nil, utm_campaign: "dark", started_at: "2016-11-14 09:02:42", is_app_event: false, app_version: nil>
[3] pry(main)> Visit.find('71baa1a4-c80c-432d-b6c1-b7d05148574d')
  Visit Load (106.8ms)  SELECT "visits".* FROM "visits" WHERE "visits"."id" = $1 LIMIT 1  [["id", "71baa1a4-c80c-432d-b6c1-b7d05148574d"]]
ActiveRecord::RecordNotFound: Couldn't find Visit with id=71baa1a4-c80c-432d-b6c1-b7d05148574d
from /Users/denstepa/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/finder_methods.rb:344:in `find_one'
```
So it looks that for this event the visit was created with a different visit_id

**Comment by ankane** [comment]
See this comment for a possible solution: https://github.com/ankane/ahoy/issues/276#issuecomment-368421611
