### ISSUE TITLE
Validation failed: User must exist

### ISSUE THREAD

**Issue by phpcitizen** [ankane/ahoy#215]
I receive Validation failed: User must exist error on a rails controller if I upgrade to 1.5.2, works on 1.5.1

``` ruby
attr_accessor :tracking_visits
```

...

``` ruby
def tracking_visits
  if @tracking_visits.empty?
    ahoy.track_visit # error here
    @tracking_visits = {
        :visit_token => current_visit.visit_token,
        :visitor_token => current_visit.visitor_token,
        :device_type => current_visit.device_type,
        :os => current_visit.os,
        :browser => current_visit.browser,
        :screen_width => current_visit.screen_width,
        :screen_height => current_visit.screen_height,
    }
  end
end
```

Please advice.

**Comment by ankane** [comment]
If you're on Rails 5, you'll need to update your user association to:

```ruby
belongs_to :user, optional: true
```

**Comment by patrykkalinowski** [comment]
I'm having the same problem on fresh Rails 5 + Devise + Ahoy with everything default

```
Started POST "/ahoy/events" for ::1 at 2016-11-14 23:58:21 +0100
Completed 422 Unprocessable Entity in 72ms (ActiveRecord: 0.0ms)

ActiveRecord::RecordInvalid (Validation failed: Visit must exist)
```

```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
```

```
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end
```

```
module Ahoy
  class Event < ActiveRecord::Base
    include Ahoy::Properties

    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user, optional: true
  end
end
```

**Comment by Nosfheratu** [comment]
@ankane Your comment helped me with a project that recently move to Rails 5, I didn't know that AR models works this way now...

**Comment by profiteer** [comment]
@patrykkalinowski I had this problem too, I fixed it by restarting the ahoy session in my browsers development console with ahoy.reset(); I think the problem is some how related to corrupted or missing cookies?

**Comment by ankane** [comment]
Cleaning up isuses

**Comment by migs120** [comment]
optional true work awsome for me thanks

**Comment by Angela-Inniss** [comment]
OMG I spent over 4 hours on this :) but thanks @ankane  your solution worked!!

**Comment by eftikharEmad** [comment]
Rails 5.0.7.2
ruby-2.3.1
and I already use `belongs_to :user, optional: true` , but still having this issue

**Comment by nonye94** [comment]
frustration.
